apiVersion: v1
kind: Service
metadata:
  name: connect-hub-service
  labels:
   app: connect-hub-service
spec:
  selector:
    app: connect-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
  