services:
  web:
    image: connect_hub:1.0
    pull_policy: if_not_present
    container_name: connect_hub_web
    environment:
      - DEBUG=True
      - PYTHON_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ../Connect-Hub:/apps
